### PR TITLE
update cabal file for ghc-9.2 support

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by bennofs** [comment]
Sorry for ignoring this PR for so long. Right now, this does not build:

```
[1 of 1] Compiling Main             ( /code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs, /code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/Main.o )

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:7:31: error:
    Module
    ‘Distribution.Package’
    does not export
    ‘PackageName(PackageName)’
  |
7 | import Distribution.Package ( PackageName(PackageName), PackageId, InstalledPackageId, packageVersion, packageName )
  |                               ^^^^^^^^^^^^^^^^^^^^^^^^

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:7:68: error:
    Module ‘Distribution.Package’ does not export ‘InstalledPackageId’
  |
7 | import Distribution.Package ( PackageName(PackageName), PackageId, InstalledPackageId, packageVersion, packageName )
  |                                                                    ^^^^^^^^^^^^^^^^^^

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:8:130: error:
    Module
    ‘Distribution.PackageDescription’
    does not export
    ‘libModules’
  |
8 | import Distribution.PackageDescription ( PackageDescription(), TestSuite(..), hsSourceDirs, exeModules, libBuildInfo, buildInfo, libModules, modulePath, exeName)
  |                                                                                                                                  ^^^^^^^^^^

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:10:41: error:
    Module
    ‘Distribution.Simple.BuildPaths’
    does not export
    ‘autogenModulesDir’
   |
10 | import Distribution.Simple.BuildPaths ( autogenModulesDir )
   |                                         ^^^^^^^^^^^^^^^^^

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:13:36: error:
    Module ‘Distribution.Simple.Utils’ does not export ‘rewriteFile’
   |
13 | import Distribution.Simple.Utils ( rewriteFile, createDirectoryIfMissingVerbose )
   |                                    ^^^^^^^^^^^

/code/hcltest/dist-newstyle/build/x86_64-linux/ghc-9.2.5/hcltest-0.3.7/setup/setup.hs:14:27: error:
    Module ‘Distribution.Text’ does not export ‘disp’
   |
14 | import Distribution.Text (disp)
   | 
 ```
 
 (using cabal v2-build on ghc 9.2.5)

**Comment by l29ah** [comment]
I have no clue, used to work for me. I didn't use ghc 9.2.5 back then though.
